name: AmanzonKindle
version: ${project.version}
main: red.man10.amanzonkindle.AmanzonKindle
api-version: 1.17
softdepend:
  - Vault
commands:
  amk:
    description: Command no setsumei
    usage: /<command>
